# Generated by Django 5.2.14 on 2026-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_remove_user_tv_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plex_api_token',
            field=models.TextField(blank=True, help_text='Plex API token, symmetrically encrypted'),
        ),
        migrations.AddField(
            model_name='user',
            name='plex_server_url',
            field=models.CharField(blank=True, help_text="Plex server URL used for library import (saved so you don't repeat it)", max_length=255),
        ),
    ]
